# Generated by Django 4.2.5 on 2024-04-24 01:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filmwork",
            options={"verbose_name": "film work", "verbose_name_plural": "film works"},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name": "genre", "verbose_name_plural": "genres"},
        ),
        migrations.AlterModelOptions(
            name="genrefilmwork",
            options={
                "verbose_name": "film genre",
                "verbose_name_plural": "film genres",
            },
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "person", "verbose_name_plural": "persons"},
        ),
        migrations.AlterModelOptions(
            name="personfilmwork",
            options={
                "verbose_name": "film person",
                "verbose_name_plural": "film persons",
            },
        ),
        migrations.RemoveConstraint(
            model_name="genrefilmwork",
            name="unique_film_work_genre",
        ),
        migrations.RemoveConstraint(
            model_name="personfilmwork",
            name="unique_film_work_person",
        ),
        migrations.RemoveIndex(
            model_name="genrefilmwork",
            name="film_work_genre_idx",
        ),
        migrations.RemoveIndex(
            model_name="personfilmwork",
            name="film_work_person_idx",
        ),
        migrations.RemoveField(
            model_name="filmwork",
            name="file_path",
        ),
        migrations.RemoveField(
            model_name="filmwork",
            name="persons",
        ),
        migrations.AddField(
            model_name="filmwork",
            name="person",
            field=models.ManyToManyField(
                through="movies.PersonFilmWork", to="movies.person"
            ),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="creation_date",
            field=models.DateField(verbose_name="creation date"),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="description",
            field=models.TextField(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="genres",
            field=models.ManyToManyField(
                through="movies.GenreFilmWork", to="movies.genre"
            ),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="rating",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
                verbose_name="rating",
            ),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="title",
            field=models.CharField(max_length=200, verbose_name="film_name"),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="type",
            field=models.CharField(
                choices=[
                    (None, "(unknown)"),
                    ("movie", "movie"),
                    ("tv_show", "tv_show"),
                ],
                default="movie",
                max_length=15,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="genre_name"
            ),
        ),
        migrations.AlterField(
            model_name="genrefilmwork",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="genrefilmwork",
            name="film_work",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.filmwork",
                verbose_name="film work",
            ),
        ),
        migrations.AlterField(
            model_name="genrefilmwork",
            name="genre",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.genre",
                verbose_name="genre",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="person",
            name="full_name",
            field=models.CharField(max_length=200, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="person",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="film_work",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.filmwork",
                verbose_name="film work",
            ),
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="person",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.person",
                verbose_name="person",
            ),
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="role",
            field=models.CharField(
                choices=[
                    (None, "(unknown)"),
                    ("actor", "actor"),
                    ("director", "director"),
                    ("writer", "writer"),
                ],
                max_length=15,
                null=True,
                verbose_name="role",
            ),
        ),
        migrations.AddIndex(
            model_name="genrefilmwork",
            index=models.Index(
                fields=["film_work"], name="genre_film_work_film_work_id"
            ),
        ),
        migrations.AddIndex(
            model_name="genrefilmwork",
            index=models.Index(fields=["genre"], name="genre_film_work_genre_id"),
        ),
        migrations.AddIndex(
            model_name="personfilmwork",
            index=models.Index(
                fields=["film_work"], name="person_film_work_film_work_id"
            ),
        ),
        migrations.AddIndex(
            model_name="personfilmwork",
            index=models.Index(fields=["person"], name="person_film_work_person_id"),
        ),
        migrations.AddConstraint(
            model_name="genrefilmwork",
            constraint=models.UniqueConstraint(
                fields=("film_work", "genre"), name="unique_film_genre"
            ),
        ),
        migrations.AddConstraint(
            model_name="personfilmwork",
            constraint=models.UniqueConstraint(
                fields=("film_work", "person", "role"), name="unique_film_work_person"
            ),
        ),
    ]
